### ISSUE TITLE
Lötstatsion besitzt keine Sicherung

### ISSUE THREAD

**Issue by scmost** [HeinzAlberto/ss_v2#4]
Einbau einer Sicherung, für einen Fehlerfall

**Comment by HeinzAlberto** [comment]
Okay, das ist sinnvoll. SMD Sicherung okay?

**Comment by HeinzAlberto** [comment]
Oder SMD Feinsicherung in einer Halterung?![IMG_20230805_224212.jpg](https://github.com/HeinzAlberto/ss_v2/assets/18151901/8fa2e495-1d2a-43ca-9239-2615bb6035c5)

**Comment by scmost** [comment]
Würde nen Haltermachen, da wenn die Sicherung ausgelößt hat, die Lötstation evtl. nicht mehr betrieben werden kann xD. Bin aber für beides offen.

**Comment by HeinzAlberto** [comment]
Das mit der Halterung gefällt mir auch besser! Dann machen wir das.

**Comment by HeinzAlberto** [comment]
Würde diese verbauen (3A): https://www.lcsc.com/product-detail/Fuses_Littelfuse-0154003-DR_C206912.html
