### ISSUE TITLE
Lötstation besitz keinen Anschluss für ESD-Schutz

### ISSUE THREAD

**Issue by scmost** [HeinzAlberto/ss_v2#5]

**Comment by HeinzAlberto** [comment]
Ja, aber woran sollte man sie verbinden? Wir können natürlich eine Buchse vorne und hinten einbauen, müssen jedoch bedenken, dass sie über die Stromversorgung nicht mit Erde verbunden ist. Halte den ESD-Schutz daher für schwierig umsetzbar und bin mir nicht über die Sinnhaftigkeit sicher.

**Comment by scmost** [comment]
Anschluss an GND? 
Ist zwar kein Erdungsanschluss, allerdings kann dennoch eine Ladung darüber abgebaut werden

**Comment by HeinzAlberto** [comment]
GND können wir machen, müssen uns nur überlegen, wo wir ihn hin packen. Wir könnten auf der Platine ein Pad zum anlöten anlegen.
